(define (adjoin-set x set)
    (cond ((null? set) (cons x '()))
          ((equal? x (car set)) set)
          ((< x (car set)) (cons x set))
          ((> x (car set)) (cons (car set) (adjoin-set x (cdr set))))))
