(define (make-account balance password)
  (define num-calls 0)
  (define (withdraw amount)
    (if (>= balance amount)
        (begin (set! balance (- balance amount))
               balance)
        "Insufficient funds"))
  (define (deposit amount)
    (set! balance (+ balance amount))
    balance)
  (define (wrong-call)
    (if (> num-calls 7)
        (call-the-cops)
        (begin (set! num-calls (+ num-calls 1)) (error "Incorrect Password"))))
  (define (dispatch pass m)
    (if (eq? pass password)
        (cond ((eq? m 'withdraw) withdraw)
              ((eq? m 'deposit) deposit)
              (else (error "Unknown request -- MAKE-ACCOUNT"
                           m)))
        (wrong-call)))
  dispatch)
