(define (rand option)
    (define rand-num 0)
    (define (generate)
        (begin (set! rand-num (rand-update rand-num)) rand-num))
    (define (reset val)
        (begin (set! rand-num val) rand-num))
    (cond ((eq? option 'generate) generate)
          ((eq? option 'reset) reset)
          (else (error "Unknown request -- RAND"))))
