(define (make-zero-crossings input-stream last-value last-avpt)
    (define (smooth stream lv)
        (let ((avpt (/ (+ (stream-car stream) lv) 2)))
            (cons-stream avpt (smooth (stream-cdr stream)
                                      (stream-car stream)))))
    (define (make-crossings stream lavpt)
        (cons-stream (sign-change-detector (stream-car stream)
                                           lavpt)
                     (make-crossings (stream-cdr stream)
                                     (stream-car stream))))
    (make-crossings (smooth input-stream last-value) last-avpt))
