(define (find-variable var c-env)
    (define (frame-loop var variables i)
        (cond ((null? variables) -1)
              ((eq? var (car variables)) i)
              (else (frame-loop var (cdr variables) (+ i 1)))))
    (define (env-loop e i)
        (if (eq? e the-empty-environment)
            'not-found
            (let ((frame-index (frame-loop var (car e) 0)))
                (if (< frame-index 0)
                    (env-loop (cdr e) (+ i 1))
                    (cons i frame-index)))))
    (env-loop c-env 0))
